#pragma once

enum eGameState
{
	Playing,
	Intro,
	Startup = 3,
	MainMenu = 5,
	Loading = 6
};

enum eMetadataHash : unsigned int
{
	eCamFollowPedCameraMetadata = 3759477553,
	eCamFirstPersonShooterCameraMetadata = 3837693093,
	eCamCinematicMountedCameraMetadata = 2185301869,
	eCamFollowVehicleCameraMetadata = 420909885,
	eCamThirdPersonPedAimCameraMetadata = 1732613077
};

enum CamPresetType
{
	CPT_BOOLEAN,
	CPT_INTEGER,
	CPT_UINTEGER,
	CPT_FLOAT,
	CPT_DOUBLE
};

enum GlobalTextEntry_t
{
	MO_FP_FOV,
	MO_FP_USE_RETICLE,
	MO_FP_MIN_PITCH,
	MO_FP_MAX_PITCH,
	MO_TP_FOV,
	MO_TP_HORZ_OFF,
	MO_TP_VERT_OFF,
	MO_TP_FOLLOW_DIST,
	MO_TP_SHAKE,
	MO_TP_MIN_PITCH,
	MO_TP_MAX_PITCH,
	MO_TP_AIMING_FOV,
	MO_TP_AIMING_HORZ_OFF,
	MO_TP_AIMING_FOLLOW_DIST,
	MO_FP_VEHICLE_FOV,
	MO_FP_VEHICLE_VERT_OFF,
	MO_FP_VEHICLE_SWITCH_WATER,
	MO_FP_VEHICLE_SWITCH_DAMAGE,
	MO_FP_VEHICLE_MIN_PITCH,
	MO_FP_VEHICLE_MAX_PITCH,
	MO_TP_VEHICLE_FOV,
	MO_TP_VEHICLE_MIN_PITCH,
	MO_TP_VEHICLE_MAX_PITCH,
	MO_TP_VEHICLE_AUTO_CENTER,
	MO_TP_VEHICLE_FOLLOW_DIST,
	MO_TP_VEHICLE_PIVOT_SCALE,
	MO_TP_VEHICLE_HORZ_OFF,
	MO_TP_VEHICLE_SHAKE
};
