#pragma once

static LPCTSTR en_us[]{
	"First Person Field of View",
	"First Person Always Use Reticle",
	"First Person Min Pitch Angle",
	"First Person Max Pitch Angle",
	"Third Person Field of View",
	"Third Person Horizontal Origin",
	"Third Person Vertical Origin",
	"Third Person Follow Distance",
	"Third Person Running Shake",
	"Third Person Min Pitch Angle",
	"Third Person Max Pitch Angle",
	"Third Person Aiming Field of View",
	"Third Person Aiming Horizontal Origin",
	"Third Person Aiming Follow Distance",
	"First Person Vehicle Field of View",
	"First Person Vehicle Vertical Origin",
	"First Person Vehicle Switch In Water",
	"First Person Vehicle Switch on Destroyed",
	"First Person Vehicle Min Pitch Angle",
	"First Person Vehicle Max Pitch Angle",
	"Third Person Vehicle Field of View",
	"Third Person Vehicle Min Pitch Angle",
	"Third Person Vehicle Max Pitch Angle",
	"Third Person Vehicle Auto Center",
	"Third Person Vehicle Follow Distance",
	"Third Person Vehicle Speed Zoom",
	"Third Person Vehicle Pivot Scale",
	"Third Person Vehicle Horizontal Origin",
	"Third Person Vehicle High Speed Shake"
};

 static LPCTSTR es_es[] {
	 u8"Campo de visión en Primera Persona",
	 u8"Usar siempre el retículo en Primera Persona",
	 u8"Ángulo de Inclinación Mínimo en Primera Persona",
	 u8"Ángulo de Inclinación Máximo en Primera Persona",
	 u8"Campo de Visión en Tercera Persona",
	 u8"Origen Horizontal en Tercera Persona",
	 u8"Origen Vertical en Tercera Persona",
	 u8"Distancia de Seguimiento en Tercera Persona",
	 u8"Agitación Corriendo en Tercera Persona",
	 u8"Ángulo de Inclinación Mínimo en Tercera Persona",
	 u8"Ángulo de Inclinación Máximo en Tercera Persona",
	 u8"Campo de Visión Apuntando en Tercera Persona",
	 u8"Origen Horizontal Apuntando en Tercera Persona",
	 u8"Distancia de Seguimiento Apuntando en Tercera Persona",
	 u8"Campo de Visión de Vehículo en Primera Persona",
	 u8"Origen Vertical de Vehículo en Primera Persona",
	 u8"Cambiar la Primera Persona de Vehículo en Agua",
	 u8"Cambiar la Primera Persona del Vehículo Destruido",
	 u8"Ángulo de Inclinación Mínimo en Vehículo en Primera Persona",
	 u8"Ángulo de Inclinación Máximo en Vehículo en Primera Persona",
	 u8"Campo de Visión en Vehículo en Tercera Persona",
	 u8"Ángulo de Inclinación Mínimo en Vehículo en Tercera Persona",
	 u8"Ángulo de Inclinación Máximo en Vehículo en Tercera Persona",
	 u8"Auto - centrado en Vehículo en Tercera Persona",
	 u8"Distancia de seguimiento de Vehículo en Tercera Persona",
	 u8"Velocidad del vehículo de la tercera persona zoom relativo",
	 u8"Escala del Pivote del Vehículo en Tercera Persona",
	 u8"Origen Horizontal en Vehículo en Tercera Persona",
	 u8"Agitación de Alta Velocidad en Vehículo en Tercera Persona"
 };

static LPCTSTR ru_ru[] {
	u8"Поле обзора (первое лицо)",
	u8"Всегда отображать прицел (первое лицо)",
	u8"Минимальный угол наклона камеры (первое лицо)",
	u8"Максиммальный угол наклона камеры (первое лицо)",
	u8"Поле обзора (третье лицо)",
	u8"Отношение камеры по горизонтали (третье лицо)",
	u8"Отношение камеры по вертикали (третье лицо)",
	u8"Дистанция камеры пешком (третье лицо)",
	u8"Дрожание камеры во время бега (третье лицо)",
	u8"Минимальный угол наклона камеры (третье лицо)",
	u8"Максиммальный угол наклона камеры (третье лицо)",
	u8"Поле обзора во время прицеливания (третье лицо)",
	u8"Отношение камеры во время стрельбы по горизонтали (третье лицо)",
	u8"Дистанция камеры во время стрельбы (третье лицо)",
	u8"Поле обзора в транспорте (первое лицо)",
	u8"Отношение камеры в автомобиле по вертикали (первое лицо)",
	u8"Не переключать камеру от первого лица, когда транспорт в воде",
	u8"Не переключать камеру от первого лица, когда транспорт уничтожен",
	u8"Минимальный угол наклона камеры в автомобиле (первое лицо)",
	u8"Максиммальный угол наклона камеры в автомобиле (первое лицо)",
	u8"Поле обзора в транспорте (третье лицо)",
	u8"Минимальный угол наклона камеры в автомобиле (третье лицо)",
	u8"Максиммальный угол наклона камеры в автомобиле (третье лицо)",
	u8"Автоцентровка в транспорте от третьего лица",
	u8"Дистанция камеры во время езды (третье лицо)",
	u8"Приближение камеры в автомобиле (третье лицо)",
	u8"Масштабирование пивота в транспорте (третье лицо)",
	u8"Отношение камеры в автомобиле по горизонтали (третье лицо)",
	u8"Дрожание камеры в машине на высоких скоростях (третье лицо)"
};

 enum GlobalTextEntry_t
 {
	 MO_FP_FOV,
	 MO_FP_USE_RETICLE,
	 MO_FP_MIN_PITCH,
	 MO_FP_MAX_PITCH,
	 MO_TP_FOV,
	 MO_TP_HORZ_OFF,
	 MO_TP_VERT_OFF,
	 MO_TP_FOLLOW_DIST,
	 MO_TP_SHAKE,
	 MO_TP_MIN_PITCH,
	 MO_TP_MAX_PITCH,
	 MO_TP_AIMING_FOV,
	 MO_TP_AIMING_HORZ_OFF,
	 MO_TP_AIMING_FOLLOW_DIST,
	 MO_FP_VEHICLE_FOV,
	 MO_FP_VEHICLE_VERT_OFF,
	 MO_FP_VEHICLE_SWITCH_WATER,
	 MO_FP_VEHICLE_SWITCH_DAMAGE,
	 MO_FP_VEHICLE_MIN_PITCH,
	 MO_FP_VEHICLE_MAX_PITCH,
	 MO_TP_VEHICLE_FOV,
	 MO_TP_VEHICLE_MIN_PITCH,
	 MO_TP_VEHICLE_MAX_PITCH,
	 MO_TP_VEHICLE_AUTO_CENTER,
	 MO_TP_VEHICLE_FOLLOW_DIST,
	 MO_TP_VEHICLE_SPEED_ZOOM,
	 MO_TP_VEHICLE_PIVOT_SCALE,
	 MO_TP_VEHICLE_HORZ_OFF,
	 MO_TP_VEHICLE_SHAKE
 };

 static LPCTSTR* langtext_array[2]{ 
	 en_us, 
	 es_es,
	 ru_ru
 };

 inline LPCTSTR getConstString(int langugageId, GlobalTextEntry_t textId)
 {
	 return langtext_array[langugageId][textId];
 }
